name: 'Merge Simpson - On PR Closed'
description: 'Handles PR closed events: cleanup labels and choose next candidate'
author: 'Peter Dodd'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  label-queue:
    description: 'Label for queued PRs'
    required: false
    default: 'mq-queue'
  label-candidate:
    description: 'Label for the PR candidate used internally'
    required: false
    default: 'mq-candidate'

runs:
  using: "composite"
  steps:
    - name: Cleanup labels from this PR
      id: cleanup-labels
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        LABEL_CANDIDATE: ${{ inputs.label-candidate }}
        LABEL_QUEUE: ${{ inputs.label-queue }}
      run: ${{ github.action_path }}/../../scripts/pr-cleanup-labels.sh

    - name: Choose next candidate
      id: choose-candidate
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        LABEL_CANDIDATE: ${{ inputs.label-candidate }}
        LABEL_QUEUE: ${{ inputs.label-queue }}
      run: ${{ github.action_path }}/../../scripts/choose-candidate.sh

