name: 'Merge Simpson - On PR Closed'
description: 'If the PR is closed, cleanup the labels and choose the next candidate'
author: 'Peter Dodd'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  label-queue:
    description: 'Label for queued PRs'
    required: false
    default: 'mq-queue'
  label-candidate:
    description: 'Label for the PR candidate used internally'
    required: false
    default: 'mq-candidate'

runs:
  using: "composite"
  steps:
    - name: Was this PR the candidate?

    - name: Cleanup Labels From This PR

    - name: Validate/Fix/Choose Candidate
