name: 'Merge Simpson - On PR Update'
description: 'Handles PR update events: validate labels, update branch, check CI, merge'
author: 'Peter Dodd'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  label-queue:
    description: 'Label for queued PRs'
    required: false
    default: 'mq-queue'
  label-candidate:
    description: 'Label for the PR candidate used internally'
    required: false
    default: 'mq-candidate'

runs:
  using: "composite"
  steps:
    # ─────────────────────────────────────────────────────────────
    # Step 1: Validate/Fix/Choose candidate
    # ─────────────────────────────────────────────────────────────
    - name: Validate/Fix/Choose candidate
      id: validate-fix-choose
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        LABEL_CANDIDATE: ${{ inputs.label-candidate }}
        LABEL_QUEUE: ${{ inputs.label-queue }}
      run: ${{ github.action_path }}/../../scripts/validate-fix-choose-candidate.sh

    # ─────────────────────────────────────────────────────────────
    # Step 2: Check if this PR is the candidate
    # ─────────────────────────────────────────────────────────────
    - name: Check if this PR is candidate
      id: is-candidate
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        LABEL_CANDIDATE: ${{ inputs.label-candidate }}
      run: ${{ github.action_path }}/../../scripts/pr-is-candidate.sh

    # ─────────────────────────────────────────────────────────────
    # Step 3: Update branch if needed (only if candidate)
    # ─────────────────────────────────────────────────────────────
    - name: Update branch if needed
      id: update-branch
      if: steps.is-candidate.outputs.is_candidate == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: ${{ github.action_path }}/../../scripts/update-branch.sh

    # ─────────────────────────────────────────────────────────────
    # Step 4: Check if CI passed (only if candidate and not updated)
    # ─────────────────────────────────────────────────────────────
    - name: Check if CI passed
      id: ci-checks
      if: steps.is-candidate.outputs.is_candidate == 'true' && steps.update-branch.outputs.updated != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: ${{ github.action_path }}/../../scripts/ci-checks-passed.sh

    # ─────────────────────────────────────────────────────────────
    # Step 5: Check if PR is mergeable (only if CI passed)
    # ─────────────────────────────────────────────────────────────
    - name: Check if PR is mergeable
      id: is-mergeable
      if: steps.is-candidate.outputs.is_candidate == 'true' && steps.update-branch.outputs.updated != 'true' && steps.ci-checks.outputs.checks_passed == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        LABEL_CANDIDATE: ${{ inputs.label-candidate }}
        LABEL_QUEUE: ${{ inputs.label-queue }}
      run: ${{ github.action_path }}/../../scripts/pr-is-mergable.sh

    # ─────────────────────────────────────────────────────────────
    # Step 6: Merge the PR (only if mergeable)
    # ─────────────────────────────────────────────────────────────
    - name: Merge PR
      id: merge-pr
      if: steps.is-candidate.outputs.is_candidate == 'true' && steps.update-branch.outputs.updated != 'true' && steps.is-mergeable.outputs.is_mergeable == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: ${{ github.action_path }}/../../scripts/merge-pr.sh

    # ─────────────────────────────────────────────────────────────
    # Step 7: Choose next candidate after merge
    # ─────────────────────────────────────────────────────────────
    - name: Choose next candidate after merge
      id: choose-candidate
      if: steps.merge-pr.outputs.merged == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        LABEL_CANDIDATE: ${{ inputs.label-candidate }}
        LABEL_QUEUE: ${{ inputs.label-queue }}
      run: ${{ github.action_path }}/../../scripts/choose-candidate.sh

